issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    # default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # extra
    - bodyclose
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - unconvert
    - unparam

run:
  timeout: 10m
