name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install
        run: go mod download
      - name: Test
        run: go test -v -race -cover .
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
